# Generated by Django 3.2.5 on 2021-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0003_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Student'), (3, 'Staffs')], default=1, max_length=10),
        ),
    ]
