# Generated by Django 3.2.5 on 2021-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
