# Generated by Django 3.2.5 on 2021-08-24 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0006_competitiontype_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='staff_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_center.staffs'),
        ),
    ]
