# Generated by Django 3.2.5 on 2021-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0008_alter_participants_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participants',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
