# Generated by Django 3.2.5 on 2021-08-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0009_auto_20210828_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
