# Generated by Django 3.2.5 on 2021-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0010_alter_competitiontype_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='person_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
