# Generated by Django 3.2.5 on 2021-09-04 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0013_alter_participants_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='staff_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
