# Generated by Django 3.2.5 on 2021-09-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0014_alter_competitiontype_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='selected_exam',
            field=models.CharField(choices=[(1, 'JEE-Mains'), (2, 'JEE-Advance'), (3, 'NEET-UG'), (4, 'UPSE-Prelims'), (5, 'UPSE-Mains')], default=1, max_length=10),
        ),
    ]
