# Generated by Django 3.2.5 on 2021-09-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0015_competitiontype_selected_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiontype',
            name='selected_exam',
        ),
    ]
