# Generated by Django 3.2.5 on 2021-09-15 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_center', '0016_remove_competitiontype_selected_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiontype',
            name='level',
        ),
        migrations.RemoveField(
            model_name='competitiontype',
            name='link',
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=255)),
                ('optionA', models.CharField(default='', max_length=200)),
                ('optionB', models.CharField(default='', max_length=200)),
                ('optionC', models.CharField(default='', max_length=200)),
                ('optionD', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('competition_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz_center.competitiontype')),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
